exclude: ^(migrations)/

substitutions:
  - &exclude
    exclude: ^(migrations)
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.6.1
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    args: [--safe, --line-length, '100']
    language_version: python3.8
    <<: *exclude
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: flake8
    args: [--max-line-length, '100']
    exclude: djath/athena_code/migrations/
    language_version: python3.8
- repo: https://github.com/asottile/pyupgrade
  rev: v1.23.0
  hooks:
  - id: pyupgrade
    language_version: python3.8
    <<: *exclude
