# Generated by Django 2.1.5 on 2019-02-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='fork',
            field=models.ForeignKey(help_text='Select a fork for this brnach', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Fork'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', help_text='Enter the name for the branch', max_length=100),
        ),
        migrations.AddField(
            model_name='fork',
            name='name',
            field=models.CharField(default='', help_text='Enter the name for the fork', max_length=100),
        ),
        migrations.AddField(
            model_name='fork',
            name='repo',
            field=models.ForeignKey(help_text='Select a repo for this fork', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Repo'),
        ),
        migrations.AddField(
            model_name='repo',
            name='summary',
            field=models.TextField(default='', help_text='Enter a brief description for this repo', max_length=1000),
        ),
        migrations.AlterField(
            model_name='repo',
            name='name',
            field=models.CharField(default='', help_text='Enter the name for the GH repo', max_length=100),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.CharField(default='', help_text='Enter the url for the GH repo', max_length=500),
        ),
    ]
