# Generated by Django 2.1.5 on 2019-02-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0002_auto_20190203_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fork',
            name='repo',
        ),
        migrations.AddField(
            model_name='fork',
            name='url',
            field=models.CharField(default='', help_text='Enter the url for the GH fork', max_length=500),
        ),
        migrations.AlterField(
            model_name='branch',
            name='fork',
            field=models.ForeignKey(help_text='Select a fork for this branch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Fork'),
        ),
        migrations.DeleteModel(
            name='Repo',
        ),
    ]
