# Generated by Django 2.1.5 on 2019-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0003_auto_20190209_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='fork',
            name='alldata',
            field=models.TextField(blank=True, help_text='Enter any additional data about the as a dict', null=True),
        ),
    ]
