# Generated by Django 2.1.5 on 2019-02-09 14:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0004_fork_alldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fork',
            name='alldata',
        ),
        migrations.AddField(
            model_name='fork',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Enter any additional data about the as a dict', null=True),
        ),
    ]
