# Generated by Django 2.1.5 on 2019-02-09 18:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0006_branch_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter the name for the repo', max_length=100)),
                ('url', models.CharField(default='', help_text='Enter the url for the GH fork', max_length=500)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Enter any additional data about the as a dict', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fork',
            name='repo',
            field=models.ForeignKey(help_text='Select a repo for this fork', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Repo'),
        ),
    ]
