# Generated by Django 2.1.5 on 2019-02-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0007_auto_20190209_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='repo',
            field=models.ForeignKey(help_text='Select a repo for this branch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Repo'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.CharField(default='', help_text='Enter the url for the GH repo', max_length=500),
        ),
    ]
