# Generated by Django 2.1.5 on 2019-02-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0008_auto_20190209_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(help_text='Select where to place this code.', path='/home/jdupuy26/Projects/athena-webinterface/django-athena/testsite')),
                ('name', models.CharField(help_text='Enter a name for this code.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.CharField(help_text='Select a problem to configure', max_length=100)),
                ('code', models.ForeignKey(help_text='Select code for this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Code')),
            ],
        ),
        migrations.AlterField(
            model_name='fork',
            name='url',
            field=models.URLField(default='', help_text='Enter the url for the GH fork', max_length=500),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.URLField(default='', help_text='Enter the url for the GH repo', max_length=500),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fork',
            field=models.ForeignKey(help_text='Select a fork for this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Fork'),
        ),
        migrations.AddField(
            model_name='code',
            name='fork',
            field=models.ForeignKey(help_text='Select a fork for this code.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Fork'),
        ),
    ]
