# Generated by Django 2.1.5 on 2019-02-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0009_auto_20190210_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='path',
            field=models.FilePathField(help_text='Select where to place this code.', path='/home/jdupuy26/Projects/athena-webinterface/django-athena/testsite/mycode'),
        ),
    ]
