# Generated by Django 2.1.5 on 2019-02-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0010_auto_20190210_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='path',
            field=models.CharField(default='/home/jdupuy26/Projects/athena-webinterface/django-athena/testsite/mycode', help_text='Select where to place this code.', max_length=500),
        ),
    ]
