# Generated by Django 2.1.5 on 2019-02-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0012_auto_20190210_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='forks',
        ),
        migrations.AddField(
            model_name='code',
            name='forks',
            field=models.ForeignKey(help_text='Select a fork for this code.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Fork'),
        ),
        migrations.RemoveField(
            model_name='fork',
            name='codes',
        ),
        migrations.AddField(
            model_name='fork',
            name='codes',
            field=models.ForeignKey(help_text='Select a code for this fork', null=True, on_delete=django.db.models.deletion.SET_NULL, to='athena_code.Code'),
        ),
    ]
