# Generated by Django 2.1.5 on 2019-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0016_auto_20190216_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='input_file',
            field=models.CharField(default='/home/jdupuy26/Projects/athena-webinterface/django-athena/testsite/jdupuy26-athena-public-version/inputs/hydro/athinput.blast', help_text='Select an input file for this configuration', max_length=500),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='prob',
            field=models.CharField(default='blast', help_text='Select a problem to configure', max_length=100),
        ),
    ]
