# Generated by Django 2.1.7 on 2019-02-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0018_auto_20190219_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='hdf5double',
        ),
    ]
