# Generated by Django 2.1.7 on 2019-02-24 15:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0019_remove_configuration_hdf5double'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='input_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Enter the input file for this problem as a dictionary.The root keys should be the blocks of the input_file.', null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='input_file',
            field=models.CharField(default='', help_text='Enter the input file name for this configuration.', max_length=500),
        ),
    ]
