# Generated by Django 2.1.7 on 2019-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0020_auto_20190224_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='input_file',
            field=models.CharField(blank=True, default='', help_text='Enter the input file for this configuration.', max_length=500),
        ),
    ]
