# Generated by Django 3.0.3 on 2020-02-16 01:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("athena_code", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="name",
            field=models.CharField(
                default="", help_text="Enter a name for this configuration.", max_length=500
            ),
        )
    ]
