# Generated by Django 3.0.3 on 2020-02-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='data',
            field=models.CharField(blank=True, help_text='Enter any additional data about the as a dict', max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='input_dict',
            field=models.CharField(blank=True, help_text='Enter the input file for this problem as a dictionary.The root keys should be the blocks of the input_file.', max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='fork',
            name='data',
            field=models.CharField(blank=True, help_text='Enter any additional data about the as a dict', max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='data',
            field=models.CharField(blank=True, help_text='Enter any additional data about the as a dict', max_length=6000, null=True),
        ),
    ]
